<?php

namespace Faculte\AdminBundle\Repository;

/**
 * ExerciceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciceRepository extends \Doctrine\ORM\EntityRepository
{
}
