<?php

namespace Faculte\AdminBundle\Repository;

/**
 * GaleriepersonnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GaleriepersonnelRepository extends \Doctrine\ORM\EntityRepository
{
}
